### ISSUE TITLE
Database creation stuck with warnings 

### ISSUE THREAD

**Issue by shaikhshahidg** [SSHVersionControl/SSHVersionControl.github.io#3]
Hi Tried Installaing both manual and composer approaches to setup GitSSH2 , Faced issues initially but somehow passed step with success on Checking System Configuration and after that tried invoking 
**php app/console doctrine:database:create**
After invoking the process is up 

> 
root      4521  0.0  0.3 476608 31348 pts/2    S+   02:09   0:00 php app/console doctrine:database:create
> 

and i am getting following logs with no progress 

> 
**(base) [root@xyz git-web-client-master]# php app/console doctrine:database:create
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pulseadmin/GitSSH2/git-web-client-master/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/pulseadmin/GitSSH2/git-web-client-master/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665**

> 

Can someone please help . 
Entries in my parameters.yaml are 
**parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 8888
    database_name: shahidvcdb
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: shahiduser
    mailer_password: shahidpassword
    locale: en
    secret: Shahid!
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true
    enable_registration: false
    secret_key: Shahid!**

**Comment by SSHVersionControl** [comment]
Hi @shaikhshahidg ,

I am afraid this project has been abandoned. I have updated the master branch with code I was working on last year, but I find I do not have time to continue working on this project.

**Comment by shaikhshahidg** [comment]
thanks for your reply ,


Regards,
Shaikh Shahid G .
+91 9503954781 (Mobile)
+91 9422083005 (Whats App)
